import Navbar from '@/components/navbar/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Nunito } from 'next/font/google'
import Modal from '@/components/modals/Modal'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={nunito.className}>
         <div>
            <Navbar />
            {/* <Modal 
                actionLabel='Submit' 
                secondaryLabel='Cancel' 
                title={"Hello World"} 
                isOpen /> */}
         </div>
        {children}
      </body>
    </html>
  )
}
